### ISSUE TITLE
Are cookies appended to the HTTP requests?

### ISSUE THREAD

**Issue by shadowfoxish** [spoonconsulting/cordova-plugin-background-upload#102]
My cordova application targets iOS and Android and we're using this plugin to upload pictures to an ASPNET Rest API service. The Application authenticates to the API using a cookie, something like ".ASPXAUTH". On Android devices, we're seeing an issue where cookies are not being appended to the uploads so they're failing. (debugging the actual requests shows 0 cookies). 

In the headers section of the config, should I be manually adding in a Cookie: .ASPXAUTH=12345blahblahblah header, or is the intention that this would happen automatically?

**Comment by azharbeebeejaun** [comment]
It should be added to the headers manually.

**Comment by shadowfoxish** [comment]
Thank you very much for answering my question, @azharbeebeejaun
