### ISSUE TITLE
Success, error event callbacks not fired

### ISSUE THREAD

**Issue by nkprince007** [spoonconsulting/cordova-plugin-background-upload#109]
> When the app is relaunched, the ids of these uploads will be emitted to the error listener.

This is not happening as expected, when I start an upload from an Angular 7 service. Without which I can't detect if or not an upload was done and as such delete the file.

**Comment by ombr** [comment]
Hi @nkprince007,

We are currently working on a new version. Could you try it and let us now if you have any issue with it.

https://github.com/spoonconsulting/cordova-plugin-background-upload/pull/106

Thanks in advance.
