### ISSUE TITLE
Can't seem to get upload to work :(

### ISSUE THREAD

**Issue by dogofpavlov** [spoonconsulting/cordova-plugin-background-upload#117]
Hello! Thank you for taking the time to create and update this plugin... I really appreciate it. 

I believe I have it setup exactly as shown in the install... but when I run the "startUpload" method, I don't see anything happening at all... no notifications, no network traffic, nothing.

`
	uploader = FileTransferManager.init({parallelUploadsLimit:2},($event)=>{
		console.log("this NEVER FIRES");
	});
	uploader.startUpload(mypayload);
`

I can't seem to get anything to happen.  I'm almost positive I've installed it correctly as I can do a "console.log(FileTransferManager)" and I can see a valid object with properties.... just nothing happens when I call a method.

I'm pretty familiar with cordova plugins but can't seem to get anywhere with this. My current project has 14 other plugins that are all working great. 

the UUID for the file... that is something I am suppose to make up correct? As well as the file key?

Thank you for your time.

**Comment by ombr** [comment]
Hi Ryan,

Could you try this branch : v2-0-0 and you can check a demo on this branch: afnetworking-spx-demo-build

And let me know if it is not working as expected ?

Thanks.

Luc

**Comment by dogofpavlov** [comment]
thank you for the reply. I actually before I saw your reply... realized that I was using the version on npm directly... after I changed it to point to the github plugin itself, now it seems things are working!

**Comment by ombr** [comment]
Great !
