### ISSUE TITLE
FileTransferManager is not defined when production build

### ISSUE THREAD

**Issue by thekily** [spoonconsulting/cordova-plugin-background-upload#13]
When I build the android app with ionic cordova build android --prod
I install it on device, then appears this error:
Uncaught ReferenceError: FileTransferManager is not defined
    at Object.335 (main.js:1)
    at e (vendor.js:1)
    at window.webpackJsonp (vendor.js:1)
    at main.js:1

It seems due to declaration var:
declare var FileTransferManager: any;

**Comment by mevinDhun** [comment]
I just tried with demo project and it built successfully using cordova cli 8.0 and ionic 3.20. Did you encounter your issue with the demo project?

**Comment by PraveenBiradar** [comment]
Yes,i encountered the issue with demo project

**Comment by mevinDhun** [comment]
@PraveenBiradar can you post your cordova/nodejs version?
