### ISSUE TITLE
Cannot install Plugin on Android

### ISSUE THREAD

**Issue by hanslbua** [spoonconsulting/cordova-plugin-background-upload#166]
Hello.

I have a problem installing the plugin in my cordova app uses Android and iOS.

On iOS there is no problem on installing the plugin, but on Android i get this Error:

`Failed to install 'cordova-plugin-background-upload': Error: cordova-plugin-background-upload cannot be added. <edit-config> changes in this plugin conflicts with <edit-config> changes in config.xml. Conflicts must be resolved before plugin can be added.`

**config.xml** 

```
<platform name="android">
		
		<content src="index.html" />
		<access origin="*" />
		<allow-navigation href="*" />
		<allow-navigation href="http://*/*" />
		<allow-navigation href="https://*/*" />
		<allow-navigation href="data:*" />
		<allow-navigation href="file:*" />
		<allow-navigation href="cdvfile:*" />
		
        <preference name="AndroidLaunchMode" value="singleInstance" />
        <allow-intent href="market:*" />
        <icon density="ldpi" src="res/icon/android/ldpi.png" />
        <icon density="mdpi" src="res/icon/android/mdpi.png" />
        <icon density="hdpi" src="res/icon/android/hdpi.png" />
        <icon density="xhdpi" src="res/icon/android/xhdpi.png" />
        <preference name="AndroidPersistentFileLocation" value="Compatibility" />
        <preference name="AndroidExtraFilesystems" value="files,files-external,documents,sdcard,cache,cache-external,assets,root" />
        <preference name="SplashScreen" value="none" />
        <preference name="loadUrlTimeoutValue" value="700000" />
        <edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge">
            <!-- The Mobile SDK requires the android:requestLegacyExternalStorage attribute. -->
            <!-- Therefore, you should set the target API level to 29 -->
            <application android:requestLegacyExternalStorage="true"/>
        </edit-config>
        <preference name="android-targetSdkVersion" value="30" />
        <preference name="android-minSdkVersion" value="22" />
    </platform>
```

But when i removed the `<edit-config>` tag i get the same erromsg.

```
"cordova": "^10.0.0",
"cordova-android": "^10.1.1",
"cordova-ios": "^6.2.0",
```

**Comment by zafirskthelifehacker** [comment]
Hello @hanslbua 

Thanks for using our plugin.

For the `requestLegacyExternalStorage` permission, you should use a `custom-preference` rather than `edit-config` as it is not the right way. Below is an example:

`<custom-preference name="android-manifest/application/@android:requestLegacyExternalStorage" value="true" />`

Also make sure that you are using Version 2 of the plugin:

`cordova plugin add @spoonconsulting/cordova-plugin-background-upload --save`

Regards,
Zafir
Spoon Consulting LTD

**Comment by dilo99** [comment]
i've the same problem with the error described by @hanslbua
i've tried to install the plugin with --force tag, but the cordova build command reveal another error:
`1: Task failed with an exception.
-----------
* Where:
Script '...\platforms\android\@spoonconsulting\cordova-plugin-background-upload\mobile-config.gradle' line: 2

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'cdvMinSdkVersion' for project ':app' of type org.gradle.api.Project.`

please help.
the version installed is 2.0.4, so le latest

**Comment by zafirskthelifehacker** [comment]
Hello @dilo99,

We have updated our plugin to support Android 12(API Level 31). You need to update the plugin to `2.0.6`.

`"@spoonconsulting/cordova-plugin-background-upload": "2.0.6"`

Make sure `cordova-android >= 10.0.0` is installed.

Regards,
Zafir
Spoon Consulting LTD

**Comment by dilo99** [comment]
Hello, thank you @zafirskthelifehacker , but the problem does not seem to be compatibility with the Android version.
We were able to find that the problem of changing the edit-config conflicting with another plugin was temporarily solvable by putting your plugin first in the list, so that it is installed first and the others below.  The second problem concerned the ext.cdvMinSdkVersion variable which at compile time, even with targetSdk 30 and not 31, was not found by your plugin.  try to reproduce this two problems.  Thank you

**Comment by sithwarrior** [comment]
@dilo99  how do you put the plugin "first in the list" ? as the package.json etc is sorted alfabetical ?

**Comment by dilo99** [comment]
@sithwarrior With "first in the list" I meant, first plugin in config.xml plugin list, that I think includes plugins in the order you declare in the config itself.
Try yourself, if you put this plugin in as my config.xml posted up here, the build fail, but If you put this plug in in top of the list in config.xml, the build works.

**Comment by sithwarrior** [comment]
@dilo99  Ill try that out, but in newish projects, the plugins are not maintained in confix.xml anymore but in package.json
But there might be a fallback, that uses the plugin list in config.xml before package.json

**Comment by zafirskthelifehacker** [comment]
Hello @dilo99,

For the problem `Could not get unknown property 'cdvMinSdkVersion' for project ':app' of type org.gradle.api.Project.`, this has been resolved in Version 2.0.6.

As for the problem `edit-config`, we will releasing a new version soon without overwriting this config.

Regards,
Zafir
Spoon Consulting LTD

**Comment by sithwarrior** [comment]
@zafirskthelifehacker  Just to clarify, does this mean that release 2.07 fixes this issue?

**Comment by zafirskthelifehacker** [comment]
Hello @sithwarrior,

In Version 2.0.7, we added support for Android 12. You can view the changelog on this link: https://github.com/spoonconsulting/cordova-plugin-background-upload/blob/v2/CHANGELOG.md

Regards,
Zafir
Spoon Consulting LTD
