### ISSUE TITLE
dependency android-storage no longer available

### ISSUE THREAD

**Issue by jrochel** [spoonconsulting/cordova-plugin-background-upload#168]
When trying to install the plugin I'm getting the following error:

```
       > Could not find com.sromku:simple-storage:1.2.0.
         Searched in the following locations:
           - https://dl.google.com/dl/android/maven2/com/sromku/simple-storage/1.2.0/simple-storage-1.2.0.pom
           - https://repo.maven.apache.org/maven2/com/sromku/simple-storage/1.2.0/simple-storage-1.2.0.pom
         Required by:
             project :app
```

The package com.sromku:simple-storage is in fact no longer available as it was hosted on the repository jcenter which no longer exists (https://mvnrepository.com/artifact/com.sromku/simple-storage).

**Comment by zafirskthelifehacker** [comment]
Hello @jrochel 

Can you please send us your configs(package.json, ....) and also specify your cordova-android version.

Also send us all the steps that you have to done to get this error so that we can reproduce it.

Regards,
Zafir
Spoon Consulting LTD

**Comment by jrochel** [comment]
Also I'm using commandlinetools-linux-7583922_latest.

**Comment by jrochel** [comment]
`cordova platform ls` yields
```
Installed platforms:
  android 10.0.1
```

**Comment by zafirskthelifehacker** [comment]
Hello @jrochel,

Can you please remove these lines:
- `"cordova-plugin-background-upload": "https://github.com/jrochel/cordova-plugin-background-upload"`
- `"cordova-plugin-background-upload": {}`

And also for the line `"@spoonconsulting/cordova-plugin-background-upload": "git+https://github.com/spoonconsulting/cordova-plugin-background-upload.git"`, use v2 branch or 2.0.7 version:
- `"@spoonconsulting/cordova-plugin-background-upload": "git+https://github.com/spoonconsulting/cordova-plugin-background-upload.git#v2"` or
- `"@spoonconsulting/cordova-plugin-background-upload": "2.0.7"` (Recommended)

Regards,
Zafir
Spoon Consulting LTD

**Comment by jrochel** [comment]
Thanks, I have done as you ask, but the problem persists. Version 2.0.7 also references in `plugin.xml` the framework `com.sromku:simple-storage:1.2.0`, which is no longer available.

I'm still getting the error:
```
     Required by:
         project :app
   > Could not find com.sromku:simple-storage:1.2.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/sromku/simple-storage/1.2.0/simple-storage-1.2.0.pom
       - https://repo.maven.apache.org/maven2/com/sromku/simple-storage/1.2.0/simple-storage-1.2.0.pom
     Required by:
         project :app
```

From which repository should this framework be downloaded?

**Comment by zafirskthelifehacker** [comment]
Hello @jrochel,

This framework is using JCenter. Have you tried to add jcenter() in your build.grade. Like this below:

repositories {
    jcenter()
}

As for JCenter Deprecration(that may effective in February 2022 - https://blog.gradle.org/jcenter-shutdown#check), we will be working on a new version for that.

Regards,
Zafir
Spoon Consulting LTD

**Comment by schematical** [comment]
Hey looks like `jcenter` is shutting down: 
https://blog.gradle.org/jcenter-shutdown

I have heard rumor they are possibly keeping it up for read only but I can tell you that as of the moment it is 502ing. @zafirskthelifehacker any ideas?

**Comment by schematical** [comment]
I was able to find that plugin on mavenCentral but there is no 4.0.0 it would appear: https://repo.maven.apache.org/maven2/net/gotev/uploadservice/

Just these versions: 
![image](https://user-images.githubusercontent.com/260698/149224771-b497c8c0-49e2-4c3d-a8eb-63c40fd728b3.png)

**Comment by schematical** [comment]
Just a heads up jcenter is back up today so the plugin can build again.
