### ISSUE TITLE
Need help for using this plugin with cordova code push

### ISSUE THREAD

**Issue by imabasghar** [spoonconsulting/cordova-plugin-background-upload#21]
Platform: iOS

After downloading and installing the latest package using code push, we restart the app. But when we restart the app, it crashes because of

File FileUploadManager.m: 
``` 
- (void)start
{
    NSURLSessionConfiguration *     configuration;
    
    NSParameterAssert(self.session == nil);                 // This line
...
```

So I was thinking if there is any way we can stop the session through the plugin before restarting the app, because I see a stop method in the same file.

**Comment by mevinDhun** [comment]
This seems to be related to reloading of the page:
[https://github.com/spoonconsulting/cordova-plugin-background-upload/issues/22](https://github.com/spoonconsulting/cordova-plugin-background-upload/issues/22)

**Comment by mevinDhun** [comment]
@imabasghar Can you try v1.0.13 on npm? This should fix your issue
