### ISSUE TITLE
App crashes on window.location.reload or window.location.href='index.html'

### ISSUE THREAD

**Issue by tbassett44** [spoonconsulting/cordova-plugin-background-upload#22]
When I reload my app from a code update in the JS world, I have been doing window.location.href='index.html', the problem with this is that it seems ios crashes when it tries to rebind/re-init FileTransferManager.init().  My guess is that this can only be bound once...but it would loose reference in the JS world when the window is reloaded.  Is there an unbind command or would it be possible to unbind, like FileTransferManager.destroy() so it can be re-inited on a JS/window reload

**Comment by assertdesignuk** [comment]
Yeah I have same issue. When the app refreshes after being in the background too long, the object is already initialised and fails to init again and causes a crash.

**Comment by assertdesignuk** [comment]
Okay I have managed to create a fix for this and will be creating a fork.

**Comment by tbassett44** [comment]
Wow, awesome, please let me know when you have it up.  Thanks @assertdesignuk !

**Comment by assertdesignuk** [comment]
Here ya go:

https://www.npmjs.com/package/cordova-plugin-background-upload-ad

**Comment by tbassett44** [comment]
Wow, thank you @assertdesignuk !  <3

**Comment by mevinDhun** [comment]
Hi, @tbassett44 I have been busy and did not check this issue. @assertdesignuk can you create a pull request for your changes?

**Comment by assertdesignuk** [comment]
> Hi, @tbassett44 I have been busy and did not check this issue. What is the reason for you to reload the page? @assertdesignuk can you create a pull request for your changes?

Sure no problem.

**Comment by tbassett44** [comment]
@mevinDhun, we reload the page when there is an update to our production JS code we want to push.  I tested @assertdesignuk's code yesterday and it seemed to fix the problem.

**Comment by mevinDhun** [comment]
@tbassett44 @assertdesignuk I have published v1.0.13 on npm. This should fix the issue.
