### ISSUE TITLE
Uploads fail due to multipart/mixed

### ISSUE THREAD

**Issue by nvahalik** [spoonconsulting/cordova-plugin-background-upload#220]
This plugin works very well on iOS but while testing on an Android 10 device, the uploads are not working for us.

Our target system is running PHP and uploads on Android fail with a redirect.

After adding:

    bodyBuilder.setType(MultipartBody.FORM);

Under 

    final MultipartBody.Builder bodyBuilder = new MultipartBody.Builder();

In `UploadTask.java` and redeploying, the uploads are working fine.

**Comment by zafirskthelifehacker** [comment]
Hello @nvahalik,

I have merged your PR and published on version `4.0.5`.

Regards,
Zafir.
