### ISSUE TITLE
File not Found error on android

### ISSUE THREAD

**Issue by abhishekporwal** [spoonconsulting/cordova-plugin-background-upload#28]
Hi,

I am using this plugin and it is working perfectly fine. The only scenario where it is failing is when i am trying to upload the images from Android Gallery. I am using cordova-plugin-telerik-imagepicker plugin to pick multiple images from the gallery and when i pass on all the images to upload to server i am getting upload error saying the file does not exist.

Thanks

**Comment by mevinDhun** [comment]
HI @abhishekporwal 
Make sure there are no spaces in the file paths you are providing to the uploader. I use same plugin in another project and the uploader works as it should. But it my case, i renamed all images to a UUID.

**Comment by abhishekporwal** [comment]
Thanks @mevinDhun. I'll double check for the spaces but i am sending the same path to the uploaded which is returned by the image picker plugin.

**Comment by ibrahimAboelsuod** [comment]
@l0stpenguin How do you make sure there is no spaces in the file paths? encoding the URL doesn't seem to have any effect.
