### ISSUE TITLE
Show notification with progress

### ISSUE THREAD

**Issue by Shtibel** [spoonconsulting/cordova-plugin-background-upload#33]
Hi there,
I am using this plugin on ionic app.
How can I show a notification of the upload progress in Android and IOS ?

Thank you.

**Comment by mevinDhun** [comment]
@Shtibel There is currently a nearly completed PR which provides progress notifications on Android:
https://github.com/spoonconsulting/cordova-plugin-background-upload/pull/32
On ios, it is not possible to show a progress bar in notification center and currently notifications are not supported for this platform.

**Comment by mevinDhun** [comment]
Upload notifications are now supported on master version
