### ISSUE TITLE
Need help for using plugin along with Multer

### ISSUE THREAD

**Issue by amittkSharma** [spoonconsulting/cordova-plugin-background-upload#4]
Trying to use the Cordova-plugin-background-upload plugin along with Multer on the server side. The key in the Multer is defined as "XNAME", how can I configure the payload in order to use it properly. I am using the plugin for the Ionic 3 app. The current payload looks like the following as suggested in the documentation of the plugin.

var payload = {
      id: filename,
      filePath: targetPath,
      serverUrl: url,
      api_key: "XNAME",
      fileKey: "XNAME",
      headers: {
        mimeType: "image/jpeg",
        'Content-Type': 'multipart/form-data'
      },
      "parameters": {
        signature: "mysign",
        timestamp: new Date().getTime()
      }

Getting the following error message on the Nodejs server:

 Unexpected field (err.code=LIMIT_UNEXPECTED_FILE)
   Error: Unexpected field

Thanks 
-Amit

**Comment by mevinDhun** [comment]
Hi amit, i have added the fileKey parameter in v1.0.6.. Please upgrade to the latest version. Also, the ```api_key``` parameter is in the wrong place in the payload it should be inside the headers object like this:

```javascript
var payload = {
    id: filename,
    filePath: targetPath,
    serverUrl: url,
    fileKey: "XNAME",
    headers: {
        api_key: "YOUR_API_KEY",
        mimeType: "image/jpeg",
        'Content-Type': 'multipart/form-data'
    },
    parameters: {
        signature: "mysign",
        timestamp: new Date().getTime()
    }
}
```

**Comment by amittkSharma** [comment]
Hi Mevin, 

Thanks for the reply and fix. But I checked the NPM page for the plugin the version stated over there is v1.0.2 and even in the releases section on Github I didn't find v1.0.6.

Thanks
-Amit

**Comment by mevinDhun** [comment]
Here it is:
[https://www.npmjs.com/package/cordova-plugin-background-upload](https://www.npmjs.com/package/cordova-plugin-background-upload)
