### ISSUE TITLE
NetworkMonitor does not work properly?

### ISSUE THREAD

**Issue by hansenundtoth** [spoonconsulting/cordova-plugin-background-upload#48]
Hey,
If i add a File without any connection and then activate cell or wifi, the plugin does not do anything.

For my understanding it should try to upload the file after the network-state changed.
I'm using your plugin with cordova and together with the "cordova-plugin-network-information"-plugin.

Kind regards
Sascha

**Comment by mevinDhun** [comment]
@hansenundtoth The plugin will store the files in a queue if there is no internet at the time of upload. On android it will monitor when a network is available and will retry automatically while on ios the system will determine the retries based on network conditions.

**Comment by hansenundtoth** [comment]
Hey, but unfortunately this doesnt work on our huawei-devices.
I've added a file in airplane-mode and after deactivating airplane-mode the app or this plugin wont retry to upload nor trigger any event-handler.
If i restart the app the plugin will trigger the error-handler as desired.

**Comment by mevinDhun** [comment]
@hansenundtoth Have you been able to reproduce this issue on other devices? Unfortunately i do not have a Huawei device to test this.

**Comment by hansenundtoth** [comment]
im able to reproduce it. Even in an Pixel-Tablet Emulator.
If i can help with any further infomation. let me know. :-)

**Comment by hansenundtoth** [comment]
Alright... i debugged a bit in my Emulator and found this:
The NetworkMonitoring is fine and works well.

This is what happens:
Step 1: I add my File(s) in airplane-mode
LOG:  D/FileTransferBG: adding upload 3231
LOG: D/FileTransferBG: Upload failed. Image added to pending list

Step 2: i disable Airplane-Mode:
LOG: D/FileTransferBG: detected network change, Connected:true
LOG : D/FileTransferBG: upload with id 3231 is already exists in upload queue. ignoring re-upload request

So my conclusion is:
If the Network-State changes you call "uploadPendingList".
This function iterates every entry and if the entry is in State "Started" or "Failed", you call method "upload" again and it should try to upload again BUT in Line 166 you are checking if this UploadID already exists and if so you quit this method. So the re-upload attempt doesnt really happen.

Is this behavoir as intended?

Kind Regards

**Comment by mevinDhun** [comment]
@hansenundtoth You are right. It should not be checking for duplicate upload from pending list in upload.
Can you try this PR to see if it fixes the issue?
https://github.com/spoonconsulting/cordova-plugin-background-upload/pull/50

**Comment by hansenundtoth** [comment]
Sure. Will be my first PR but ill do my best.
