### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by CharlesPoullain** [spoonconsulting/cordova-plugin-background-upload#5]
Hello, I am trying to use your awesome plugin to upload video on a server from a mobile app. 
It actually worked on ios but not in android. I don't know why it isn't working to me. Should I use a different  configuration on the payload file for both os ?

Best Regards

**Comment by mevinDhun** [comment]
Hi, are you getting any specific errors? Can you provide some logs? Did you try the sample app in the repo?

**Comment by CharlesPoullain** [comment]
Thanks you for you prompt response.
I am currently use Monaca not Ionic.
When I tryed to upload a video on android, the upload.error tell me : "execute failed". And when I checked my device logs, it seems to be linked to the permissions : " App onError: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Camera/VID_20180103_144532.mp4 (Permission denied)"

**Comment by CharlesPoullain** [comment]
Thanks you for your prompt response.
I just fix the issus. I added some android permissions to read the storage.
Thanks a lot !
