### ISSUE TITLE
possible feature: abort running upload

### ISSUE THREAD

**Issue by iwan-uschka** [spoonconsulting/cordova-plugin-background-upload#6]
Hi there, do you plan to include a function for aborting running requests? Just asking because i evaluate to use other solutions than [cordova-plugin-file-transfer](https://github.com/apache/cordova-plugin-file-transfer). Thanks

**Comment by mevinDhun** [comment]
Hi, 
There is a method to cancel an upload:
```javascript
let uploader = FileTransferManager.init();
uploader.removeUpload(uploadId, ()=>{
    //upload aborted
  }, err=> console.error("could not remove upload"));
```

I'll update the docs to make it more clear.

**Comment by iwan-uschka** [comment]
Thanks for letting me know. I only searched for "abort" or "cancel", not for "remove" in the sources :) great. cheers
