### ISSUE TITLE
Uploads are processed concurrently not only 1 at a time on iOS

### ISSUE THREAD

**Issue by omardoma** [spoonconsulting/cordova-plugin-background-upload#63]
The docs says that only 1 concurrent upload is supported at the moment which implies that the plugin queues uploads, while this is true for Android as it does process one upload at a time, I found that on iOS queuing does not occur and all uploads are processed at the same time. 

is there something I am missing or that is not the intended behavior?

**Comment by mevinDhun** [comment]
On ios the queue management is done by the system daemon. The concurrent limit has been hardcoded to 1 as seen here:
https://github.com/spoonconsulting/cordova-plugin-background-upload/blob/master/src/ios/FileTransferBackground.m#L221

According to apple docs, using `HTTPMaximumConnectionsPerHost ` will limit the concurrent connections.
https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1407597-httpmaximumconnectionsperhost?language=objc

Are you trying to upload to different hosts?

**Comment by omardoma** [comment]
No I am uploading to the same exact serverUrl but uploads queue only on Android, on iOS all of them start right away

**Comment by omardoma** [comment]
I guess this is the reason: https://stackoverflow.com/questions/51607333/nsurlsession-httpmaximumconnectionsperhost-not-working-as-expected

I am using HTTP 2

**Comment by omardoma** [comment]
HTTP 2 uses only 1 Connection and multiplexes a lot of requests on it, that's why to the plugin I am indeed using 1 connection only. 

Queueing will only work with HTTP 1.1
