### ISSUE TITLE
upload.serverResponse is a JSON string not parsed on Android

### ISSUE THREAD

**Issue by omardoma** [spoonconsulting/cordova-plugin-background-upload#64]
On iOS, the upload serverResponse is a parsed JSON into an object literal, but on Android its an unparsed JSON string.

It results in an inconsistent API that forces me to handle it like that:

```
// Workaround that Android's response is a JSON string
map(upload =>  
    this.isAndroid
    ? JSON.parse(upload.serverResponse)
    : upload.serverResponse
 )
```

**Comment by mevinDhun** [comment]
Yes it is a valid bug. We are currently working on a new version which should fix all these issues and have Travis tests setup. The v2 version uses `AFNetworking` internally on ios.
If you wanna have a look, checkout the `afnetworking` and `android_v2` branch.

**Comment by omardoma** [comment]
Alright great to hear that the plugin is being improved as me and my team rely on it for a lot of things.

Thanks for the hardwork, and if you need me to beta test something would be more than happy to help out.
