### ISSUE TITLE
two issues

### ISSUE THREAD

**Issue by peratik** [spoonconsulting/cordova-plugin-background-upload#8]
Hello.

1. Referring to the docs:
 ```
var payload = {
     "id": "sj5f9"
     "filePath": "/storage/emulated/0/Download/Heli.divx",
     "fileKey": "file",
     "serverUrl": "http://requestb.in/14cizzj1",
     "headers": {
         "api_key": "asdasdwere123sad"
     },
     "parameters": {
         "signature": "mysign",
         "timestamp": 112321321
     }
 };

 uploader.startUpload(options);
```

It should be:  `uploader.startUpload(payload );`

2. Please add response utf-8 support. If response is in utf-8 it displays ? charchters.

Thank you

**Comment by gkimpson** [comment]
@peratik did you manage to get this plugin to work? If so you would you be able to share this working app?

**Comment by peratik** [comment]
no, i used official cordova file transfer plugin

**Comment by gkimpson** [comment]
@peratik have you used the official file transfer plugin with background processes? As that is what I am trying to achieve - a process that will only run when required e.g not have the app running constantly only when there is something to transfer

**Comment by peratik** [comment]
First I tried to use your plugin, because it did not support utf--8 I removed plugin and installed official cordova file transfer plugin.

**Comment by mevinDhun** [comment]
@peratik Can you provide with more details? What content is the server returning? Do you have sample which i can try to reproduce the issue?

**Comment by mevinDhun** [comment]
Type in README fixed.
