### ISSUE TITLE
Video upload corrupted

### ISSUE THREAD

**Issue by CyberCyclone** [spoonconsulting/cordova-plugin-background-upload#86]
Hi,

Can someone please explain why this is added to the start of the file and also at the end?

`--Boundary-8BDE7C70-89B7-40AA-B889-3B17B2C8793F
Content-Disposition: form-data; name="file"; filename="1585023559770.mp4"
Content-Type: application/octet-stream`

I don't see how any file could open correctly after having this text added to the file. Is this a side-effect of me forcing the plugin to use "PUT" instead of "POST"?

If so then that's fine as I've commented out those sections from the forked version of this plugin.

**Comment by ombr** [comment]
Hi,

The upload is form encoded. You have to decode it to get your file.

Luc

**Comment by CyberCyclone** [comment]
That's where it's gone wrong for me. I'm uploading directly to S3 and since it dumps it as is due to it being serverless, the added data is kept there.

**Comment by ombr** [comment]
Hum, this is an issue, could you try to use the afnetworking branch ? (It is a new version of the plugin ?) Thanks.

**Comment by maxcodefaster** [comment]
> That's where it's gone wrong for me. I'm uploading directly to S3 and since it dumps it as is due to it being serverless, the added data is kept there.

How did you device the formdata to use the PUT method?
