### ISSUE TITLE
Out Of Order Uploads.

### ISSUE THREAD

**Issue by piercers** [spoonconsulting/cordova-plugin-background-upload#88]
We're queuing up a large set of files to be uploaded and need to preserve the order in which they're added. Unfortunately, we're seeing some chunks of the list of items uploaded out of order. For example in a batch of 100 items, the first third would upload in the correct order, then it would choose a random one from later in the list, then it would jump to the last third before finishing up the rest.

Is there any way to strictly enforce the order of a list of items added through `startUpload`?

**Comment by ombr** [comment]
Hi,

Could you explain your use case. Why do you need to keep the order ? (I am trying to understand why it should be usefull ?)

Thanks.

Luc

**Comment by piercers** [comment]
Hi Luc!

Users on our client side are able to customize the order of images taken before the application uploads them, and the API we're communicating with assumes the order in which it receives photos is the order set by the client.

Does that help?

**Comment by piercers** [comment]
This is good information, thank you very much.

Your recommendation is along the same lines as one option we had considered as well so we'll probably go with that: have a middleware service enforce the order.

Super easy to use plugin -- thanks for the time!

**Comment by ombr** [comment]
@piercers you are welcome, you can try the new version which should be released soon, on afnetworking branch)
